### ISSUE TITLE
Dropdown not working on iPad / iPhone devices

### ISSUE THREAD

**Issue by CatherineTrevor** [CatherineTrevor/lead-generator-calculator#18]
![issue_dropdown](https://user-images.githubusercontent.com/76033080/123055924-ababfe00-d406-11eb-9aa7-f8512658e9b7.jpg)

Upon testing on a tablet, the dropdown options do not select the option that the user selects; it is random. This also happens when testing on an iPhone, on Safari or Chrome.

After researching this issue, it would appear to be a common problem using the Materialize template.

https://github.com/Dogfalo/materialize/issues/6464

**Comment by CatherineTrevor** [comment]
Materialize solution of .browser-default added to all dropdowns within account and campaign management. This initially caused a related issue of the label not disappearing when an option is selected, so small text has been added and styled in line with the existing labels on the other fields.

The affected fields now work as intended on iPad and iPhones, using the browser default class.

![issue_18_resolve](https://user-images.githubusercontent.com/76033080/123085793-f471b000-d422-11eb-8caa-a54fc8dac500.jpg)

**Comment by ignasdamunskis** [comment]
It is caused by the dropdown content animation. I created this [npm package](https://www.npmjs.com/package/materialize-css-helper) to solve this and other materialize issues. Please try it
